### ISSUE TITLE
Restructuring of the branches in drones repository

### ISSUE THREAD

**Issue by iamarkaj** [JdeRobot/drones#108]
According to the new structure of the drones repository as decided by @pariaspe and @nkhedekar, there will be different branches for different ROS distros.

`noetic-devel` for ROS-noetic
`melodic-devel` for ROS-melodic
`kinetic-devel` for ROS-kinetic (EOL)

Since, the `noetic-devel` and `melodic-devel` are already running and maintained, the `master` branch needs to be deleted and a new branch `kinetic-devel` must be created for ROS-kinetic. Although the kinetic development has reached its End Of Life (EOL) but can still be installed if required.

**Comment by pariaspe** [comment]
Some cleaning is also needed after merging huge PR about Tello drone compatibility
