### ISSUE TITLE
[drone_teleop] Adapt GUI to new mixed control in drone_wrapper

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/drones#12]

**Comment by diegomrt** [comment]
Hi @pariaspe. Just checked your new drone_teleop GUI proposal. Looks good. Just a few suggestions:

- I'll use at least two digits after the decimal point in both pose and velocity.
- I'll add, after the three components, the reference frame in which they're given (maybe the descriptive mav frame would be a good option).
- I'll also include angular velocity
- Maybe showing them clustered and writing complete labels -Pos Info (M) -> Position (m) and same for velocity- would help reading them

Thanks!

**Comment by pariaspe** [comment]
Done in pr #36
