### ISSUE TITLE
Take off using mixed control

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/drones#13]

**Comment by diegomrt** [comment]
Could you elaborate on how to configure now the takeoff height?

**Comment by pariaspe** [comment]
My fault, there was an error in the variable naming and I fixed it locally (in my catkin / src). I forgot to fix it in the package too. PR #17  fixes this.

You can set the takeoff height with `h` parameter:
```python3
drone = DroneWrapper()
drone.takeoff(h=DESIRED_HEIGHT)
```
