### ISSUE TITLE
[drone_teleop]Show position and velocities info

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/drones#16]

**Comment by diegomrt** [comment]
Hi @pariaspe. Just checked your new drone_teleop GUI proposal. Looks good. Just a few suggestions:

- I'll use at least two digits after the decimal point in both pose and velocity.
- I'll add, after the three components, the reference frame in which they're given (maybe the descriptive mav frame would be a good option).
- I'll also include angular velocity
- Maybe showing them clustered and writing complete labels -Pos Info (M) -> Position (m) and same for velocity- would help reading them

Thanks!

**Comment by pariaspe** [comment]
Hi @diegomrt , 

Thanks for you feedback. What do you think about this new gui?

![new_teleop](https://user-images.githubusercontent.com/35956525/81060970-cd30ea00-8ed3-11ea-9e57-810e37703dd1.png)

I am not sure where the reference frame is. I am reading it from the header of PoseStamped and TwistStamped msgs (both from local position topic). Is it ok?

**Comment by diegomrt** [comment]
Hi @pariaspe 

The new GUI now looks great to me. Maybe I'll just point out somehow that the fourth velocity component is angular z speed, in rad/s. Now it's not clear. Use a new line or insert it between the actual data and the JdeRobot logo. 

Regarding frames, its ok to use the ROS ones. Probably the mav frame has no interest here.

**Comment by pariaspe** [comment]
> Hi @pariaspe
> 
> The new GUI now looks great to me. Maybe I'll just point out somehow that the fourth velocity component is angular z speed, in rad/s. Now it's not clear. Use a new line or insert it between the actual data and the JdeRobot logo.
> 
> Regarding frames, its ok to use the ROS ones. Probably the mav frame has no interest here.

Nice! What about this one then?

![teleop](https://user-images.githubusercontent.com/35956525/81072892-22c2c200-8ee7-11ea-8d36-276124e23169.png)

**Comment by diegomrt** [comment]
Perfect @pariaspe, I think we've got it!
