### ISSUE TITLE
Build failing for kinetic and xenial dev

### ISSUE THREAD

**Issue by nkhedekar** [JdeRobot/drones#32]
http://build.ros.org/job/Mdev__jderobot_drones__ubuntu_bionic_amd64/
http://build.ros.org/job/Kdev__jderobot_drones__ubuntu_xenial_amd64/

**Comment by nkhedekar** [comment]
This might be related to https://github.com/JdeRobot/assets/issues/48

**Comment by pariaspe** [comment]
I've just received this:

> Jenkins build is back to normal : Mdev__jderobot_drones__ubuntu_bionic_amd64 #11
> Jenkins build is back to normal : Kdev__jderobot_drones__ubuntu_xenial_amd64 #24

**Comment by nkhedekar** [comment]
I guess it must be a versioning issue then as mentioned https://github.com/JdeRobot/assets/issues/48#issuecomment-628260183
