### ISSUE TITLE
[drone_teleop] Position in GUI partly synced with mavros topic

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/drones#39]
Some components of the Position information box of the new GUI freeze and never recover back. Interestingly, some others keep synced with `/mavros/local_position/pose` topic

The screenshot below was taken when x,y were frozen but z was still syncinc properly: 

![Captura de pantalla de 2020-05-29 18-44-51](https://user-images.githubusercontent.com/35877889/83287291-b4210d80-a1e1-11ea-9b33-de82db70934b.png)

**Comment by pariaspe** [comment]
Hi @diegomrt ,

This issue seems similar to #38. Would not be the same problem?

**Comment by diegomrt** [comment]
Hi @pariaspe 

Yes, I also think this particular behaviour about partial sync in the new box probably comes from the same issue described in #38. So we'll close it once #38 is solved.
