### ISSUE TITLE
[drones] support for IRIS drone in ROS noetic

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/drones#80]
so it may be used both in RoboticsAcademy and also in VisualCircuit. We will create a noetic-branch

**Comment by RUFFY-369** [comment]
Hi @jmplaza ,
I would like to contribute to this issue. Regarding the workflow, should the installation instructions for Ubuntu 20.04 (Focal) release, ROS Noetic be updated first?

Regards,
Prakarsh

**Comment by pariaspe** [comment]
Hi @RUFFY-369, 

It would be nice if you create an _**installation20.md**_ following the installation steps of the [previous version](https://github.com/JdeRobot/drones/blob/master/installation18.md).

**Comment by RUFFY-369** [comment]
Hi @pariaspe ,
Yeah sure, will work on it.

**Comment by RUFFY-369** [comment]
Hi @pariaspe ,
I have created a PR (#84 ) regarding creating an **_installation20.md_**. Please review it.

Regards,
Prakarsh

**Comment by pariaspe** [comment]
jderobot_drones has been migrated to noetic ([branch](https://github.com/JdeRobot/drones/tree/noetic-devel)). Installation instructions has been also updated in #84 and #86.
Thanks for your contribution @RUFFY-369, @iamarkaj
