### ISSUE TITLE
RoboticsAcademy drone exercises in ROS1-Noetic and Gazebo-11

### ISSUE THREAD

**Issue by iamarkaj** [JdeRobot/drones#87]
**Tested and ran all drone exercises in ROS1-Noetic & Gazebo-11.**

https://user-images.githubusercontent.com/40225765/116651170-2d038900-a9a0-11eb-953d-53f52e6764e7.mp4

However, could not fix this 
```
rosdep install --from-paths . --ignore-src --rosdistro noetic -y
```
![rosdep-install-error](https://user-images.githubusercontent.com/40225765/116550849-dac95600-a914-11eb-9c1b-9ec30f9d02c3.png)
*For now, I skipped that*

**Troubleshooting**
- **rqt_gui error** can be fixed by  adding "--" before perspective file args inside the launch file. For example, inside exercises/position_control.launch change
```
<node name="rqt_gui" pkg="rqt_gui" type="rqt_gui" respawn="false" output="screen" args="perspective-file $(arg perspective)"/>
```
to
```
<node name="rqt_gui" pkg="rqt_gui" type="rqt_gui" respawn="false" output="screen" args="--perspective-file $(arg perspective)"/>
```
- **could not find drone_wrapper_class error** can be fixed temporarily by 
```
export PYTHONPATH=$PYTHONPATH:~/catkin_ws/src/rqt_drone_teleop/src/rqt_vel_teleop:~/catkin_ws/src/drone_wrapper/src/drone_wrapper
```

**Comment by iamarkaj** [comment]
**Update: fixed the rqt_gui problem**
Adding "--" before perspective file args inside the launch file fixed it.

Inside position_control.launch
```
<node name="rqt_gui" pkg="rqt_gui" type="rqt_gui" respawn="false" output="screen" args="perspective-file $(arg perspective)"/>
```
to
```
<node name="rqt_gui" pkg="rqt_gui" type="rqt_gui" respawn="false" output="screen" args="--perspective-file $(arg perspective)"/>
```

**Comment by RUFFY-369** [comment]
Hi @iamarkaj , @pariaspe ,
This is in reference to the error caused by executing the following command:
`rosdep install --from-paths . --ignore-src --rosdistro noetic -y`
which @iamarkaj mentioned.

I looked into it and found that there are some distribution specific dependencies of Ubuntu releases and seems that python-rosdep doesn't exist in Ubuntu 20.04, i.e., Focal. Here is the reference to the [TypeScript](https://github.com/ros-tooling/setup-ros/blob/master/src/package_manager/apt.ts#L37) file which mentions it. And they metioned a [pull](https://github.com/ros-tooling/setup-ros/pull/147/files) which they already created regarding it.

The above installation (as shown in image) failed as ROS Noetic utilises python3 unlike Melodic which uses python2.
Did you (@iamarkaj) already install the python/python3-rospkg and is there any package on your system with python-rospkg as dependency instead of python3-rospkg?

**Comment by iamarkaj** [comment]
![image](https://user-images.githubusercontent.com/40225765/116797392-06119800-ab03-11eb-814d-027697ef4ee9.png)

Do let me know if this helps @RUFFY-369

**Comment by RUFFY-369** [comment]
Hi @iamarkaj ,
Can you try to execute the `rosdep install --from-paths . --ignore-src --rosdistro noetic -y` from a different directory instead of catkin_ws? And tell if 'python-rospkg' installation error still occurs.
And also is python3 your default python?

**Comment by iamarkaj** [comment]
Hi @RUFFY-369 
AFAIK, we need to make sure we are inside catkin workspace for rosdep to look at all the packages in the src directory and find all of the dependencies they have. Then it will recursively install the dependencies. Correct me if I am wrong.

And for the python version, I am attaching a ss.
![python-version](https://user-images.githubusercontent.com/40225765/116802111-f78ca600-ab2d-11eb-9abb-14b27dfa6299.png)

**Comment by RUFFY-369** [comment]
Hi @iamarkaj ,
The reason  for asking to rosdep install from another directory was to confirm that is there any package in your workspace with python-rospkg as  a dependency which is causing the error. 
And regarding  being in catkin_ws for rosdep to find package dependencies, one can try it from a different catkin_ws to confirm the same.

**Comment by pariaspe** [comment]
Hi guys,
I've been working on a new docker image based on noetic lately, so I hope my little experience with noetic can help. I got some errors configuring my catkin_ws, but I solved them installing **python3-catkin-tools** and **python3-rosdep**. Notice that python2 (and pkgs related to it) are not needed anymore with Ubuntu 20.04 and ROS Noetic.
Rosdep is used to check if all ROS pkgs have their required dependencies already installed in the host machine. It is used with source packages, so it has to be run inside the catkin_ws folder.

PS: I hope to review (and merge) all your PRs soon. Sorry for the delay.

**Comment by iamarkaj** [comment]
Hi @pariaspe 
Can I work on the RoboticsAcademy Docker image or is it done?

**Comment by pariaspe** [comment]
> Hi @pariaspe
> Can I work on the RoboticsAcademy Docker image or is it done?

It is almost done, I hope finish testing and pushing it soon.

**Comment by pariaspe** [comment]
Soled in JdeRobot/RoboticsAcademy#1027
