### ISSUE TITLE
Update README with new noetic branch

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/drones#92]
Current changes in master branch (#90) have caused a jenkins build [fail](https://build.ros.org/job/Kdev__jderobot_drones__ubuntu_xenial_amd64/50/console). It seems that gazebo pkg it is not found in drone_assets. 
Since Kinetic branch is on EOL status, and new changes won't be included in kinetic release, I propose to update README removing kinetic tags and adding noetic new ones.

Drone_assets tags should be also added.

**Comment by jmplaza** [comment]
perfect, good forward movement

**Comment by pariaspe** [comment]
Bionic jenkins build has also [failed](https://build.ros.org/job/Mdev__jderobot_drones__ubuntu_bionic_amd64/38/console). Drone_assets' CMakeLists.txt have to be reviewed as it is raising the error.

**Comment by iamarkaj** [comment]
PR #93
